export default {
  '01d': require('../assets/owma/01d.png'),
  '01n': require('../assets/owma/01n.png'),
  '02d': require('../assets/owma/02d.png'),
  '02n': require('../assets/owma/02n.png'),
  '03d': require('../assets/owma/03d.png'),
  '03n': require('../assets/owma/03n.png'),
  '04d': require('../assets/owma/04d.png'),
  '04n': require('../assets/owma/04n.png'),
  '09d': require('../assets/owma/09d.png'),
  '09n': require('../assets/owma/09n.png'),
  '10d': require('../assets/owma/10d.png'),
  '10n': require('../assets/owma/10n.png'),
  '11d': require('../assets/owma/11d.png'),
  '11n': require('../assets/owma/11n.png'),
  '13d': require('../assets/owma/13d.png'),
  '13n': require('../assets/owma/13n.png'),
  '50d': require('../assets/owma/50d.png'),
  '50n': require('../assets/owma/50n.png'),
};
